title: Gustav Masch 
logo: "/images/Headshot2.2.jpg?raw=true" 
description: >
  <h4> Contact Information </h4>
  <a href="https://www.linkedin.com/in/gustav-masch/">LinkedIn</a> 
  <br>
  <a href="https://www.GitHub.com/gustav-masch/">GitHub</a>  
  <br>
  <p> gustav.masch@gmail.com </p>
  <br>
    
theme: jekyll-theme-minimal
